name: splooking3
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cloud_firestore: ^3.5.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  firebase_auth: ^3.11.0
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_picker: ^2.0.5
  flutter_screenutil: ^5.5.4
  font_awesome_flutter: ^10.2.1
  hooks_riverpod: ^2.0.1
  intl: ^0.17.0
  pedantic_mono: ^1.20.0
  twitter_login: ^4.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/switch_icon.png

  uses-material-design: true
